language: cpp

compiler:
    - gcc

# old fashioned way until the libs are available...
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:george-edison55/precise-backports -y
  - sudo add-apt-repository ppa:apokluda/boost1.53 -y
  - sudo apt-get update -qq

env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: "D3sPCm/RIAURESmi8IDbTuiqVSvPwKIjf6oQjyascC0QCUbLGdsPlYYriGV2OpFY/Z+PlL5Pcc6WVpcqnXE24DAfV5n3VBlWAY7BfDeL+G77LTbell8woFcSn0rfmwhlvJ6/HE4ZsFelMJ+yA9o6Gk+v8uKMwO+EcI6LnQiiH/4Doii8Rxquj0j8i0A5m97+zAnAZsKXOToC4+G8qI1xIuENqvDUacG5L+XXY0c/5WKE+rE3nuDCBnqNICqE0i9LjGopkQdBI6GQtrvaT/5FK+s8iBtujTQ8JVZX7HSvlBAeXk96Qjrhbve0KD9vj1vGzespQQVPmY5Z9s5B/F/t1ebAS92bz33N57CSjpmqj/G1bo8UYpHKTlMBksmtOo5U1pm+4pNR2mkJhA63ZvCWOKgzbk8qXzV/nxFvHa2cz3GhXZ/BwCNkycUrKJIw3OdEcc1DrCyHpB3LQrmS0WsSLzWgMVTGBOrlNrCopvcYHpydGRm+6eYEMZ82KJsmXgwG9LkELVNz0+yI8INI8sDKK5YWQ6grg56F4JVEiQucbqJG2OoQsmNaIAA2/m+voi3VlL01rB86k+5XQAkUMVczB1YqRiakLzMaUImcyytvdJtnzn2S2bT/txLQrHb4/cwn1IFXHpOAvMC1MazGIiuXw+IzNWH+BEtBxhfCgzNEKYo="

addons:
  coverity_scan:
    project:
      name: johnbeard/haxeditor
      description: "HaxEditor"
    notification_email: john.j.beard+coverity@gmail.com
    build_command_prepend: cmake -DCMAKE_BUILD_TYPE=Debug .
    build_command: cmake --build .
    branch_pattern: coverity_scan

#
#addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#      - george-edison55-precise-backports
#    packages:
#      - cmake
#      - cmake-data
#      - libwxgtk2.8-dev
#      - libsigc++-2.0-dev
#      - g++-4.8
#      - gcc-4.8

install:
    - sudo apt-get install -y libwxgtk3.0-dev g++-4.8 gcc-4.8 libsigc++-2.0-dev cmake cmake-data lcov rubygems
    - sudo apt-get install -y libboost-system1.53-dev libboost-filesystem1.53-dev libboost-iostreams1.53.dev
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
    - gem install lcoveralls
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

before_script:
    - gcc --version
    - g++ --version
    - cmake --version
    - lcov --version

script:
    - if [ "${COVERITY_SCAN_BRANCH}" == 1 ]; then
        echo "Not building on Coverity scan branch";
        exit 0;
      fi
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    # make sure everything builds
    - make -j2 all
    # make sure the tests run (clean coverage beforehand)
    - make -j2 coverage_clean check

after_success:
    # abort if this is a coverity scan build
    - >
      if [ "${COVERITY_SCAN_BRANCH}" == 1 ]; then
        echo "Not building on Coverity scan branch"
        exit 0
      fi
      # generate coverage info from any tests that ran
    - make coverage
      # Report code coverage to coveralls.io
    - lcoveralls --retry-count 5 --root=. $TRAVIS_BUILD_DIR/build/coverage.info
